### ISSUE TITLE
How to modify request header?

### ISSUE THREAD

**Issue by darr1s** [cybozu/WebUI#23]
Hey! Thanks for the lib, very clean and simple API indeed. Just wondering if it already support modifying every request header.

**Comment by Kyome22** [comment]
@darr1s Hi, thanks for your PR.
Since the WebUI's only responsibility is related to views, there are no plans to provide any convenient functions about URL session.
Currently, you need to inject headers into `URLRequest` before  loading.

```swift
var request = URLRequest(url: URL(string: "https://...")!)
request.allHTTPHeaderFields = ["key" : "value"]
proxy.load(request: request)
```

I think it would be a good idea to create a model that manages URLRequest.
